In [6]:
import numpy as np
from sklearn import linear_model
import math
import pandas as pd
from word2number import w2n

In [30]:
df=pd.read_excel(r'C:\Users\HP\Desktop\house.xlsx')
#df=pd.DataFrame(r'C:\Users\HP\Desktop\house.)

In [31]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [11]:
df['bedrooms']

0    3.0
1    4.0
2    NaN
3    3.0
4    5.0
Name: bedrooms, dtype: float64

In [16]:
df['bedrooms']=df['bedrooms'].fillna(math.floor(df['bedrooms'].median()))

In [17]:
df['bedrooms']

0    3.0
1    4.0
2    3.0
3    3.0
4    5.0
Name: bedrooms, dtype: float64

In [18]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [19]:
reg=linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']],df['price'])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [20]:
reg.coef_

array([   137.25, -26025.  ,  -6825.  ])

In [21]:
reg.intercept_

383724.99999999994

In [28]:
reg.predict([[3000,3,40]])

array([444400.])

In [52]:
df1=pd.read_excel(r'C:\Users\HP\Desktop\house.xlsx',sheet_name='Sheet2')
df1

experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         NaN                7   72000
7     eleven         7.0                8   80000

In [53]:
df1['test_score']=df1['test_score'].fillna(math.floor(df1['test_score'].median()))

In [54]:
df1

experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         8.0                7   72000
7     eleven         7.0                8   80000

In [1]:
#pip install word2number

  Running setup.py install for word2number: started
    Running setup.py install for word2number: finished with status 'done'



You are using pip version 19.0.3, however version 21.0.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.


In [8]:
print(w2n.word_to_num('eleven'))

11


In [25]:
df1.loc[df1['experience']=='five']


experience  test_score  interview_score  salary
2       five         6.0                7   60000

In [55]:
df1

experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         8.0                7   72000
7     eleven         7.0                8   80000

In [56]:
df1['experience']=df1['experience'].fillna('zero')

In [35]:
for i in range(len(df1['experience'])):
    df1['experience'][i]= w2n.word_to_num(df1['experience'][i])

c:\users\hp\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [57]:
df1

experience  test_score  interview_score  salary
0       zero         8.0                9   50000
1       zero         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         8.0                7   72000
7     eleven         7.0                8   80000

In [48]:
df1.loc[2,'experience']

'five'

In [60]:
for i in range(len(df1['experience'])):
    df1.loc[i,'experience']= w2n.word_to_num(df1.loc[i,'experience'])

In [59]:
w2n.word_to_num(df1.loc[3,'experience'])

2

In [61]:
df1

experience  test_score  interview_score  salary
0          0         8.0                9   50000
1          0         8.0                6   45000
2          5         6.0                7   60000
3          2        10.0               10   65000
4          7         9.0                6   70000
5          3         7.0               10   62000
6         10         8.0                7   72000
7         11         7.0                8   80000

In [63]:
reg1=linear_model.LinearRegression()
reg1.fit(df1[['experience','test_score','interview_score']],df1['salary'])


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [64]:
reg1.coef_

array([2812.95487627, 1845.70596798, 2205.24017467])

In [65]:
reg1.intercept_

17737.263464337695

In [66]:
reg1.predict([[2,9,6]])

array([53205.96797671])

In [67]:
reg1.predict([[12,10,10]])

array([92002.18340611])